version: "2"
services:

  apache:
    image: edyan/apache:2.4
    volumes:
        - ${MOODLE_DOCKER_WWWROOT}:/var/www/html
        - ./behatfaildumps:/var/www/behatfaildumps
        - ${ASSETDIR}/apache/faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf
        - ./assets/apache/vhost.conf:/etc/apache2/sites-available/vhost.conf
        - ./assets/apache/custom.conf:/etc/apache2/conf-enabled/custom.conf
        - ./assets/apache/error.log:/var/log/apache2/error.log
    depends_on:
      - db
      - mailhog

  phpfpm:
    image: zitoa/moodle-php-fpm
    depends_on:
      - db
      - mailhog
    volumes:
      - ${MOODLE_DOCKER_WWWROOT}:/var/www/html
      - ./assets/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./assets/php-fpm/php-error.log:/var/log/php-error.log
      - ./assets/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: moodle
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_WEB_PORT: "${MOODLE_DOCKER_WEB_PORT}"

  exttests:
    image: moodlehq/moodle-exttests

  selenium:
    image: "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX}:2.53.1"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:ro"

  mailhog:
    image: mailhog/mailhog
