version: "2"
services:
  phpfpm:
    volumes:
      - "${ASSETDIR}/apache/mailhog.conf:/etc/apache2/conf-enabled/apache2_mailhog.conf"
    depends_on:
      - mailhog
  mailhog:
    image: mailhog/mailhog
